// <auto-generated />
using System;
using MatDock.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatDock.Core.Data.Migrations
{
    [DbContext(typeof(MatDockDbContext))]
    [Migration("20260905214007_AddGitRepo")]
    partial class AddGitRepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MatDock.Core.Entities.BackupSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BackupTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopContainers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolumesCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupSchedule", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.BackupTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedSmbPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmbDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmbDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmbHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmbShare")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmbUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BackupTarget", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.DockerEnvironment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPrivateKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPrivateKeyPassphrase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCheckMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSudo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Environment", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.GitCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("GitCredential", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.GitRepo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GitCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("GitRepo", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.NotificationSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedSmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SmtpUseTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("MatDock.Core.Entities.Stack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComposeYaml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitComposePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GitCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitRepoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SyncJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("SyncJobId");

                    b.HasIndex("Name", "EnvironmentId")
                        .IsUnique()
                        .HasFilter("\"UpdateState\" <> 0");

                    b.ToTable("Stack", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.StackTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposeYaml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("StackTemplate", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.SyncJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cron")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GitCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitRepoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PruneRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PullImages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebhookToken")
                        .IsUnique()
                        .HasFilter("\"UpdateState\" <> 0");

                    b.ToTable("SyncJob", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.SyncJobItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComposePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("SyncJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncJobId");

                    b.ToTable("SyncJobItem", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"UpdateState\" <> 0");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSession", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.VolumeBackup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BackupScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BackupTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupTargetName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEnvironmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolumeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VolumeName");

                    b.ToTable("VolumeBackup", (string)null);
                });

            modelBuilder.Entity("MatDock.Core.Entities.UserSession", b =>
                {
                    b.HasOne("MatDock.Core.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatDock.Core.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
